[[headers]]
  for = "sw.js"
  [headers.values]
    Cache-Control = "max-age=0, must-revalidate, public"

[[headers]]
  for = "*.webmanifest"
  [headers.values]
    Cache-Control = "max-age=0, must-revalidate, public"

[[headers]]
  for = "average-color.js"
  [headers.values]
    Cache-Control = "public, max-age=604800"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=604800"

[[headers]]
  for = "*.svg"
  [headers.values]
    Cache-Control = "public, max-age=604800"